### PR TITLE
the warwick clients should be made aware of the replica set

### PR DESCRIPTION
**Pull request by edgarcosta**
the warwick clients should be made aware of the replica set

### CODE REVIEW

**Comment by JohnCremona** [comment]
I hope this can wait until Wednesday

**Comment by edgarcosta** [comment]
Yes, it can.

**Comment by JohnCremona** [comment]
By the way, with the new default config file I cannot run lmfdb locally since it times out connecting to the replicas (I think):

pymongo.errors.ServerSelectionTimeoutError: m1.lmfdb.xyz:27017: timed out,warwick.lmfdb.xyz:37010: timed out,m0.lmfdb.xyz:27017
: timed out

so I have to put back the old blank for replicaset.  Is this just temporary?

**Comment by edgarcosta** [comment]
I will look into that ASAP, which is in a couple of hours after I teach.

**Comment by edgarcosta** [comment]
You cannot run locally with the replica set flag.
For that you need to be able to access warwick.lmfdb.xyz:37010 and only a short list of ips has access to that port.

**Pull request merged**
