### PR TITLE
mongod.conf for starting mongodb and hook script

### PR DESCRIPTION
**Pull request by edgarcosta**
Hello again,
- using mongod.conf for starting mongodb, now I triple checked the config file :)
- I added the hook script for post-receive

### CODE REVIEW

**Comment by JohnCremona** [comment]
I am happy to merge this, as it would take effect anyway without pulling it to the server and restarting mongo.  Before that I would like Harald and/or Jonathan to comment since they set up the original.  I'll forward my notification email to them.

**Comment by haraldschilly** [comment]
@JohnCremona asked me to comment. well, I don't remember that much about this. Sounds good to have a config file, so let's go ahead :-)

**Comment by edgarcosta** [comment]
ping

**Comment by JohnCremona** [comment]
Sorry, I forgot about this.  After merging and pulling to lmfdb@warwick I will add a link to the conf file in the home directory, replace lmfdb.git/hooks/post-receive with a link to this one.

Then I will restart the mongod process.

**Comment by JohnCremona** [comment]
I did not in fact replace the post-receive hook since it refers to /home/lmfdbweb/ which does not exist on this machine (and that was the only change).  If that matters I could make /home/lmfdbweb a link to /home/lmfdb.
Restarting the mongo server: not untill I have confirmed that it is not currently being used -- I think Samuele might be uploading data.

**Comment by JohnCremona** [comment]
The config file DID NOT WORK.  (This explains the fact that mongod was not  running for the last 5-10 minutes).  It complained about not recognising the replication option in the file.  I made sure taht I running the correct version of mongo (3.2.1).

**Comment by edgarcosta** [comment]
I'm looking into it!

**Pull request merged**
